# Generated by Django 4.2 on 2025-10-03 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_image', models.ImageField(blank=True, null=True, upload_to='exam_papers/')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='answer_keys/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_paper', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluator.exampaper')),
            ],
        ),
    ]
